config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  resources :categories do
    member do
      get :delete
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end
  
  

  match 'about', to: "main#about", via: :get
  match 'hello', to: "main#hello", via: :get

  # get 'main/index'
  # get 'tasks/index'
  # get 'tasks/new'
  # get 'tasks/edit'
  # get 'tasks/show'
  # get 'tasks/delete'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end

  def about
    @created_by = "Kevin"
    @id = params['id']
    @page = params[:page]
  end

  def hello
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @page = params[:page].to_i
    @tasks = Task.order(:position)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @count = Task.count
    @task = Task.new(position: @count + 1)
  end

  def create
    @task = Task.new(task_params)
    if @task.save 
      redirect_to tasks_path
    else
      render("new")
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render("edit")
    end
  end

  def delete
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:name, :position, :completed, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>

<ul>
    <%@categories.each do |category|%>
        <li><%=category.name%></li>
    <%end%>
</ul>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/about.html.erb
<h2>About</h2>
<p>Description of the task manager</p>
<p>Created by <%= @created_by %></p>

<%= link_to "home", { controller: "main", action: "index" } %> <br />

ID: <%= @id%> <br />
Page: <%= @page%> <br />

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Hello World</p>

<%= link_to "tasks", tasks_path(page: 1) %>
<%= link_to "about", about_path(page: 5, id: 20) %>

<%= link_to "categories", categories_path %>

app/views/tasks/_form.html.erb
<table summary="Task form fields">
            <tr>
                <th>Name</th>
                <td><%= f.text_field(:name) %></td>
            </tr>
            <tr>
                <th>Position</th>
                <td><%= f.text_field(:position) %></td>
            </tr>
            <tr>
                <th>Completed</th>
                <td><%= f.check_box(:completed) %></td>
            </tr>
            <tr>
                <th>Description</th>
                <td><%= f.text_area(:description) %></td>
            </tr>
</table>

app/views/tasks/delete.html.erb
<%= link_to("Back to list", tasks_path, class: "back-link")%>

<div class="tasks delete">
    <h2>Delete Task</h2>

    <%= form_for(@task, method: 'delete') do |f|%>
        <p>Are you sure you want to permanently delete this task?</p>
        <p><%= @task.name%></p>

        <div class="form-buttons">
            <%= f.submit("Delete Task") %>
        </div>
    <%end%>
</div>

app/views/tasks/edit.html.erb
<%= link_to("Back to list", tasks_path, class: "back-link")%>

<div class="tasks edit">
    <h2>Edit task</h2>
    <%= form_for(@task) do |f| %>
        <%= render(partial: "form", locals: { f: f })%>
        <div class="form-buttons">
            <%= f.submit("Edit Task")%>
        </div>
    <% end %>
</div>

app/views/tasks/index.html.erb
<%= link_to "Back to homepage", {controller: "main", action: "index"} %> <br/>

<div class="tasks index">
    <h2>Tasks</h2>

    <%= link_to("Create new task", new_task_path, class: 'action new') %>

    <table class="listing" summary="Task list" style="width: 100%;">
        <tr class="header" style="width: 100%;">
            <th>#</th>
            <th>Task</th>
            <th>Completed</th>
            <th>Category</th>
            <th>Actions</th>
        </tr>
        <% @tasks.each do |task| %>
        <tr style="width: 100%;">
            <td><%= task.position%></td>
            <td><%= task.name%></td>
            <td><%= task.completed? ? 'Yes' : 'No'%></td>
            <td><%= task.category&.name || '-'%></td>
            <td class='actions'>
                <%= link_to("Show", task_path(task), class: "action show") %>
                <%= link_to("Edit", edit_task_path(task), class: "action edit") %>
                <%= link_to("Delete", delete_task_path(task), class: "action delete") %>
            </td>
        </tr>
        <%end%>
    </table>
</div>

app/views/tasks/new.html.erb
<%= link_to("Back to list", tasks_path, class: "back-link")%>

<div class="tasks new">
    <h2>Create task</h2>
    <%= form_for(@task) do |f| %>
        <%= render(partial: "form", locals: { f: f })%>
        <div class="form-buttons">
            <%= f.submit("Create Task")%>
        </div>
    <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to("Back to list", tasks_path, class: 'back-link') %>

<div class="tasks show">
    <h2>Show task</h2>

    <div class="actions">
        <%= link_to('Edit', edit_task_path(@task))%>
        <%= link_to('Delete', delete_task_path(@task))%>
    </div>

    <table summary="T^ask detail view">
        <tr>
            <th>Name</th>
            <td><%= @task.name%></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%= @task.position%></td>
        </tr>
        <tr>
            <th>Completed</th>
            <td><%= @task.completed? ? 'Yes' : 'No'%></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><%= @task.description%></td>
        </tr>
    </table>

</div>